logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://mutsa-db.c9c6sgcw26xh.ap-southeast-2.rds.amazonaws.com:3306/mutsa_board
    username: gwanghwi
    password: gwang12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # 콘솔에 sql 출력
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: "base64:V0lLMm9GQ3h6cE1Bc3l2U1dQb2R6U0dqS1h6cTZlRFRkUm9xQnZ4dVZySk1qYzZMS0hQZ0E9PQ=="
    expiration-ms: 3600000
